### ISSUE TITLE
adding the license file 

### ISSUE THREAD

**Issue by engshahrad** [cristiklein/gdinc-experiment#1]
Hey Cristian, 

I was just going over the repo and it seems that the license file is missing. It could be that you forgot to push it. Let me know if you need me to do a PR for it. 

Thanks, 
Mohammad

**Comment by cristiklein** [comment]
Hey Mohammad,

Great to hear from you and good to hear that you are still interested in this line of work. Please do a PR, as I have no clue what license is most suitable for such work.

Cheers,
Cristian

**Comment by engshahrad** [comment]
Thanks for your prompt response, Cristian. Just requested. 

Closing this issue. :)
